### ISSUE TITLE
Error trying to select pdb file

### ISSUE THREAD

**Issue by mpharrigan** [peastman/openmm-setup#1]
```
14:53:47.913 ReferenceError: optionChanged is not defined 1 selectFiles:1:1
	onchange http://localhost:5000/selectFiles:1:1
```

edit: this is in the javascript console. The ui does nothing (does not fill out the "pdb" box)

**Comment by jchodera** [comment]
Was this resolved by a PR or commit? I think this works for me now.

**Comment by peastman** [comment]
Yes, it's fixed now.
